services:
  client:
    image: h2o_client
    container_name: client
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  server:
    image: h2o_server
    container_name: server
    build:
      context: ./backend/poppy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/poppy
      SPRING_DATASOURCE_USERNAME: h2o
      SPRING_DATASOURCE_PASSWORD: s10p31c106
    networks:
      - h2o-network
    restart: always

networks:
  h2o-network:
    driver: bridge