services:
  mariadb:
    build: 
      context: .
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "poppy"
    ports:
      - "3306:3306"
    restart: always
  mongo:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: h2o
    restart: always
    
  server:
    image: h2o_server
    container_name: server
    build:
      context: ./backend/poppy
    volumes:
      - /home/ubuntu/maria-data:/app/data
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-container:3306/poppy
      - SPRING_DATASOURCE_USERNAME=h2o
      - SPRING_DATASOURCE_PASSWORD=s10p31c106
    restart: always

  client_user:
    image: h2o_client_user
    container_name: client-user
    build:
      context: ./frontend/user
    ports:
      - "3000:80"
  client_manager:
    image: h2o_client_manager
    container_name: client-manager
    build:
      context: ./frontend/poppy
    ports:
      - "3001:80"

volumes:
  mariadb-data:

