services:
  mariadb:
    image: mariadb
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: poppy
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  server:
    image: h2o_server
    container_name: server
    build:
      context: ./backend/poppy
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-container:3306/poppy
      - SPRING_DATASOURCE_USERNAME=h2o
      - SPRING_DATASOURCE_PASSWORD=s10p31c106
    restart: always

#  client:
#    image: h2o_client
#    container_name: client
#    build:
#      context: ./frontend
#    ports:
#      - "3000:3000"

networks:
  backend:

volumes:
  mariadb-data:

