services:
  mariadb:
    image: mariadb
    hostname: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ../../init.sql:/docker-entrypoint-initdb.d/init.sql
#      - mariadb_data:/var/lib/mysql
    networks:
      - h2o_network

#  client:
#    image: h2o_client
#    container_name: client
#    build:
#      context: ./frontend
#    ports:
#      - "3000:3000"

#volumes:
#  mariadb_data:

networks:
  h2o_network: